export const SEARCH_MOVIE_REQUESTED = "SEARCH_MOVIE_REQUESTED";
export const SEARCH_MOVIE_FINISHED = "SEARCH_MOVIE_FINISHED";

export const SEARCH_STRING_CHANGED = "SEARCH_STRING_CHANGED";

export const PAGE_CHANGED = "PAGE_CHANGED";

export const VIEW_MOVIE_SELECTED = "VIEW_MOVIE_SELECTED";

export const MOVIE_DETAILS_REQUESTED = "MOVIE_DETAILS_REQUESTED";
export const MOVIE_DETAILS_COMPLETED = "MOVIE_DETAILS_COMPLETED";

export const CLEARED_MOVIE_DETAIL = "CLEARED_MOVIE_DETAIL";

export const LOADED_GENRES_REQUESTED = "LOADED_GENRES_REQUESTED";
export const LOADED_GENRES_COMPLETED = "LOADED_GENRES_COMPLETED";
