export const SEARCH_MOVIE_REQUESTED = "SEARCH_MOVIE_REQUESTED";
export const SEARCH_MOVIE_FINISHED = "SEARCH_MOVIE_FINISHED";
export const SEARCH_STRING_CHANGED = "SEARCH_STRING_CHANGED";
export const PAGE_CHANGED = "PAGE_CHANGED";
